### ISSUE TITLE
Add Flag functionality for Newsfeed

### ISSUE THREAD

**Issue by ericljpemberton** [Calligre/server#50]
In order to make the Newsfeed truly usable attendees need to be able to flag offensive posts and allow moderators (through the Organizer app) to delete them.

This would most likely involve the following:
- Adding a current_user_flagged (to work much like current_user_likes so they can't flag it multiple times
- Adding a num_flagged to tell how many users have flagged the post (Organizers could sort by most flagged)
- Adding API calls to flag it of unflag it (from attendee perspective (much like likes)
- Adding API request to fetch all that have been flagged (in organizer app)
- Adding API request to delete post if moderator deems it inappropriate (in organizer app)

**Comment by kyl191** [comment]
Storage:
DynamoDB doesn't support (really) support select where flagged = true. So, we will have a new `flagged` table that just contains the ID of each flagged post.

The posts will have an additional `flags` attribute, much like the current `likes` attribute. It will store a list of the users that flagged the post.

@ericljpemberton Since the list is unsorted, what is the utility of have a count?

API:
Flag/unflag will be pretty much be a clone of like/unlike.

Fetch all: What gets returned to the organizer app will be an unsorted dict of the form 
```
{ 
postid: {
  flagger_count: int,
  content: string
}
}
```
(The `flagger_count` part will be pending a 'why do we need this' discussion.)

Deletion will be performed by calling the existing deletion endpoint (so DELETE /social/postid/). The owned check will be changed to check ownership, or admin/mod privileges. 

@TheKevJames how do we check capabilities? There doesn't appear to be an existing check for them.

**Comment by TheKevJames** [comment]
No current checks for capabilities (all we've done so far is `@requires_auth`).

Capability check would be: get current user -> ensure `user.capabilities >= required_capabilities`
